runtime: nodejs16 # or another supported version

# env values
env_variables:
  DB_URI: mongodb+srv://myinstructor:myinstructor123@my-instructor-cluster.hnbqrf0.mongodb.net/MyInstructor?retryWrites=true&w=majority
  JWT_EXPIRE_DAY: 365d
  JWT_SECRET: b8d98529d6a61a9f2907e736d4858cb4a5efe5554fa0803b12e94103b5d61fb9
  STRIPE_KEY: sk_test_51Lw6rGLGvcb0YzQkMUAN8ZAGFe6vVeIlDgxSSR2FnYwMfxKEvKxfv0twsSZ1CdWX3wwgSDK3n8Cv3BzUej1rLK8E00bjfD0idA
  SIB_API_KEY: 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
  AGREEMENT_ID: 63a587514a2533c3104a7eaa
